// frontend/js/game.js

const SUITS_DATA = {
    SPADES:   { displayChar: "♠", cssClass: "spades",   fileNamePart: "spades",   sortOrder: 4 },
    HEARTS:   { displayChar: "♥", cssClass: "hearts",   fileNamePart: "hearts",   sortOrder: 3 },
    CLUBS:    { displayChar: "♣", cssClass: "clubs",    fileNamePart: "clubs",    sortOrder: 2 },
    DIAMONDS: { displayChar: "♦", cssClass: "diamonds", fileNamePart: "diamonds", sortOrder: 1 }
};
const RANKS_LOGIC_DISPLAY = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const RANK_FILENAME_PART = {
    "A": "ace", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7",
    "8": "8", "9": "9", "10": "10", "J": "jack", "Q": "queen", "K": "king"
};
const RANK_VALUES = { "2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"J":11,"Q":12,"K":13,"A":14 };
const HAND_TYPES = { HIGH_CARD:0,PAIR:1,TWO_PAIR:2,THREE_OF_A_KIND:3,STRAIGHT:4,FLUSH:5,FULL_HOUSE:6,FOUR_OF_A_KIND:7,STRAIGHT_FLUSH:8,THIRTEEN_CARDS_SPECIAL_BASE:100,SIX_PAIRS_PLUS:101,THREE_FLUSHES_THIRTEEN:102,THREE_STRAIGHTS_THIRTEEN:103,ALL_SMALL:104,ALL_BIG:105,SAME_COLOR:106,THREE_SETS_OF_TRIPS:107,FIVE_PAIRS_AND_TRIPS:108,TWELVE_ROYALS:109,DRAGON:110,ROYAL_DRAGON:111 };
const HAND_TYPE_MESSAGES = { [HAND_TYPES.HIGH_CARD]:"乌龙",[HAND_TYPES.PAIR]:"对子",[HAND_TYPES.TWO_PAIR]:"两对",[HAND_TYPES.THREE_OF_A_KIND]:"三条",[HAND_TYPES.STRAIGHT]:"顺子",[HAND_TYPES.FLUSH]:"同花",[HAND_TYPES.FULL_HOUSE]:"葫芦",[HAND_TYPES.FOUR_OF_A_KIND]:"铁支",[HAND_TYPES.STRAIGHT_FLUSH]:"同花顺",[HAND_TYPES.SIX_PAIRS_PLUS]:"六对半",[HAND_TYPES.THREE_FLUSHES_THIRTEEN]:"三同花（特殊）",[HAND_TYPES.THREE_STRAIGHTS_THIRTEEN]:"三顺子（特殊）",[HAND_TYPES.ALL_SMALL]:"全小",[HAND_TYPES.ALL_BIG]:"全大",[HAND_TYPES.SAME_COLOR]:"凑一色",[HAND_TYPES.THREE_SETS_OF_TRIPS]:"三套三条",[HAND_TYPES.FIVE_PAIRS_AND_TRIPS]:"五对三条",[HAND_TYPES.TWELVE_ROYALS]:"十二皇族",[HAND_TYPES.DRAGON]:"一条龙",[HAND_TYPES.ROYAL_DRAGON]:"至尊清龙" };
const CARD_IMAGE_PATH_PREFIX = 'images/cards/';
const CARD_IMAGE_EXTENSION = '.png';
const UNKNOWN_CARD_FILENAME = `unknown${CARD_IMAGE_EXTENSION}`;

function getCardImageFilename(card){if(typeof RANK_FILENAME_PART==='undefined'||typeof SUITS_DATA==='undefined'||typeof CARD_IMAGE_EXTENSION==='undefined'||typeof UNKNOWN_CARD_FILENAME==='undefined'){console.error("FATAL: Constants missing in getCardImageFilename.");return 'error_constants.png';}if(!card||typeof card.rank!=='string'||typeof card.suitKey!=='string'){return UNKNOWN_CARD_FILENAME;}const rK=card.rank.toUpperCase();const rP=RANK_FILENAME_PART[rK];const sI=SUITS_DATA[card.suitKey];const sP=sI?sI.fileNamePart:null;if(!rP){return `unknown_rank_${card.rank.toLowerCase()}${CARD_IMAGE_EXTENSION}`;}if(!sP){return `unknown_suit_${card.suitKey.toLowerCase()}${CARD_IMAGE_EXTENSION}`;}return `${rP}_of_${sP}${CARD_IMAGE_EXTENSION}`;}
function getCardImagePath(card){if(typeof CARD_IMAGE_PATH_PREFIX!=='string'||typeof UNKNOWN_CARD_FILENAME!=='string'){console.error("FATAL: Path prefix missing in getCardImagePath.");return 'error_prefix/path.png';}const fN=getCardImageFilename(card);if(typeof fN!=='string'||fN.trim()===""){return CARD_IMAGE_PATH_PREFIX+UNKNOWN_CARD_FILENAME;}return CARD_IMAGE_PATH_PREFIX+fN;}
function getCardBackImagePath(){if(typeof CARD_IMAGE_PATH_PREFIX!=='string'||typeof CARD_IMAGE_EXTENSION!=='string'){return 'error_prefix/back.png';}return CARD_IMAGE_PATH_PREFIX+'back'+CARD_IMAGE_EXTENSION;}
function getRankValue(card,aceAsOne=false){if(!card?.rank)return 0;const rU=card.rank.toUpperCase();if(aceAsOne&&rU==="A")return 1;return RANK_VALUES[rU]||0;}
function sortHandCardsForDisplay(cards){if(!Array.isArray(cards))return[];return[...cards].sort((a,b)=>{const rA=getRankValue(a),rB=getRankValue(b);if(rA!==rB)return rB-rA;const sA=SUITS_DATA[a.suitKey]?.sortOrder||0,sB=SUITS_DATA[b.suitKey]?.sortOrder||0;return sB-sA;});}
function sortCardsByRankValue(cards,aceAsOne=false,ascending=false){if(!Array.isArray(cards))return[];return[...cards].sort((a,b)=>(getRankValue(a,aceAsOne)-getRankValue(b,aceAsOne))*(ascending?1:-1));}

function evaluateThirteenCardSpecial(thirteenCards) { /* ... (Placeholder - Implement your 13-card special hand logic) ... */ return null; }

function evaluateHand(cards){if(!cards||!Array.isArray(cards)||(cards.length!==3&&cards.length!==5)){return{type:HAND_TYPES.HIGH_CARD,message:"无效牌数",ranks:[],originalCards:cards,isSpecial:false};}if(cards.some(c=>!c||typeof c.rank==='undefined'||typeof c.suitKey==='undefined')){return{type:HAND_TYPES.HIGH_CARD,message:"牌数据错误",ranks:[],originalCards:cards,isSpecial:false};}const n=cards.length;const sR=sortCardsByRankValue(cards,false,false);const pR=sR.map(c=>getRankValue(c));const sS=cards.map(c=>c.suitKey);const iF=(n===5||n===3)&&new Set(sS).size===1;let iS=false;let sHCr=0;if(n===5||n===3){const rFSaL=cards.map(c=>getRankValue(c,true)).sort((a,b)=>a-b);const uRFS=[...new Set(rFSaL)];if(uRFS.length>=n){if(n===5&&uRFS[0]===1&&uRFS[1]===2&&uRFS[2]===3&&uRFS[3]===4&&uRFS[4]===5){iS=true;sHCr=5;}else{const uAHd=[...new Set(pR)].sort((a,b)=>b-a);for(let i=0;i<=uAHd.length-n;i++){let iSq=true;for(let j=0;j<n-1;j++){if(uAHd[i+j]!==uAHd[i+j+1]+1){iSq=false;break;}}if(iSq){iS=true;sHCr=uAHd[i];break;}}}}}const rC={};pR.forEach(r=>rC[r]=(rC[r]||0)+1);const cS=Object.values(rC).sort((a,b)=>b-a);const dRS=Object.keys(rC).map(Number).sort((a,b)=>b-a);let hT=HAND_TYPES.HIGH_CARD;let rFC=[...pR];let sHI={};if(n===5){if(iF&&iS){hT=HAND_TYPES.STRAIGHT_FLUSH;sHI.highCardRank=sHCr;rFC=sHCr===5?[5,4,3,2,1]:pR.filter(r=>r<=sHCr&&r>sHCr-5).sort((a,b)=>b-a);}else if(cS[0]===4){hT=HAND_TYPES.FOUR_OF_A_KIND;sHI.quadRank=dRS.find(r=>rC[r]===4);sHI.kicker=dRS.find(r=>rC[r]===1);rFC=[sHI.quadRank,sHI.kicker].filter(r=>r!==undefined);}else if(cS[0]===3&&cS[1]===2){hT=HAND_TYPES.FULL_HOUSE;sHI.threeRank=dRS.find(r=>rC[r]===3);sHI.pairRank=dRS.find(r=>rC[r]===2);rFC=[sHI.threeRank,sHI.pairRank];}else if(iF){hT=HAND_TYPES.FLUSH;rFC=pR;}else if(iS){hT=HAND_TYPES.STRAIGHT;sHI.highCardRank=sHCr;rFC=sHCr===5?[5,4,3,2,1]:pR.filter(r=>r<=sHCr&&r>sHCr-5).sort((a,b)=>b-a);}else if(cS[0]===3){hT=HAND_TYPES.THREE_OF_A_KIND;sHI.threeRank=dRS.find(r=>rC[r]===3);sHI.kickers=pR.filter(r=>r!==sHI.threeRank).sort((a,b)=>b-a).slice(0,2);rFC=[sHI.threeRank,...sHI.kickers];}else if(cS[0]===2&&cS[1]===2){hT=HAND_TYPES.TWO_PAIR;const pS=dRS.filter(r=>rC[r]===2).sort((a,b)=>b-a);sHI.highPair=pS[0];sHI.lowPair=pS[1];sHI.kicker=dRS.find(r=>rC[r]===1);rFC=[sHI.highPair,sHI.lowPair,sHI.kicker].filter(r=>r!==undefined);}else if(cS[0]===2){hT=HAND_TYPES.PAIR;sHI.pairRank=dRS.find(r=>rC[r]===2);sHI.kickers=pR.filter(r=>r!==sHI.pairRank).sort((a,b)=>b-a).slice(0,3);rFC=[sHI.pairRank,...sHI.kickers];}}else if(n===3){if(cS[0]===3){hT=HAND_TYPES.THREE_OF_A_KIND;sHI.threeRank=pR[0];rFC=[sHI.threeRank];}else if(cS[0]===2){hT=HAND_TYPES.PAIR;sHI.pairRank=dRS.find(r=>rC[r]===2);sHI.kicker=dRS.find(r=>rC[r]===1);rFC=[sHI.pairRank,sHI.kicker].filter(r=>r!==undefined);}}return{type:hT,ranks:rFC.filter(r=>r!==undefined&&r!==null),message:HAND_TYPE_MESSAGES[hT],originalCards:cards,isSpecial:false,...sHI};}
function compareHandInfos(h1,h2){if(!h1||!h2||typeof h1.type==='undefined'||typeof h2.type==='undefined')return 0;const s1=h1.type>=HAND_TYPES.THIRTEEN_CARDS_SPECIAL_BASE,s2=h2.type>=HAND_TYPES.THIRTEEN_CARDS_SPECIAL_BASE;if(s1&&!s2)return 1;if(!s1&&s2)return-1;if(h1.type!==h2.type)return h1.type>h2.type?1:-1;switch(h1.type){case HAND_TYPES.STRAIGHT_FLUSH:case HAND_TYPES.STRAIGHT:return h1.highCardRank>h2.highCardRank?1:(h1.highCardRank<h2.highCardRank?-1:0);case HAND_TYPES.FOUR_OF_A_KIND:if(h1.quadRank!==h2.quadRank)return h1.quadRank>h2.quadRank?1:-1;return h1.kicker>h2.kicker?1:(h1.kicker<h2.kicker?-1:0);case HAND_TYPES.FULL_HOUSE:if(h1.threeRank!==h2.threeRank)return h1.threeRank>h2.threeRank?1:-1;return h1.pairRank>h2.pairRank?1:(h1.pairRank<h2.pairRank?-1:0);case HAND_TYPES.FLUSH:case HAND_TYPES.HIGH_CARD:for(let i=0;i<Math.min(h1.ranks.length,h2.ranks.length);i++){if(h1.ranks[i]!==h2.ranks[i])return h1.ranks[i]>h2.ranks[i]?1:-1;}return 0;case HAND_TYPES.THREE_OF_A_KIND:if(h1.threeRank!==h2.threeRank)return h1.threeRank>h2.threeRank?1:-1;if(h1.originalCards.length===5&&h1.kickers&&h2.kickers){for(let i=0;i<Math.min(h1.kickers.length,h2.kickers.length);i++){if(h1.kickers[i]!==h2.kickers[i])return h1.kickers[i]>h2.kickers[i]?1:-1;}}return 0;case HAND_TYPES.TWO_PAIR:if(h1.highPair!==h2.highPair)return h1.highPair>h2.highPair?1:-1;if(h1.lowPair!==h2.lowPair)return h1.lowPair>h2.lowPair?1:-1;return h1.kicker>h2.kicker?1:(h1.kicker<h2.kicker?-1:0);case HAND_TYPES.PAIR:if(h1.pairRank!==h2.pairRank)return h1.pairRank>h2.pairRank?1:-1;const k1=h1.originalCards.length===5?h1.kickers:(h1.kicker!==undefined?[h1.kicker]:[]);const k2=h2.originalCards.length===5?h2.kickers:(h2.kicker!==undefined?[h2.kicker]:[]);if(k1&&k2){for(let i=0;i<Math.min(k1.length,k2.length);i++){if(k1[i]!==k2[i])return k1[i]>k2[i]?1:-1;}}return 0;default:return 0;}}
function checkDaoshui(top,middle,bottom){if(!top||!middle||!bottom||top.isSpecial||middle.isSpecial||bottom.isSpecial){console.warn("checkDaoshui with invalid hands.");return true;}if(compareHandInfos(top,middle)>0){return true;}if(compareHandInfos(middle,bottom)>0){return true;}return false;}
